In [ ]:
import numpy as np
import csv
from pathlib import Path
import scipy.io
from scipy.signal import resample_poly
import pandas as pd


In [3]:
from pathlib import Path
files = []
example_mat = Path("example.mat")
directory = Path('raw_data/ball/20k')
output_dir = Path('mat_data/ball/20k')
for file in directory.iterdir():
    if file.is_file():
        files.append(file)

In [4]:
import numpy as np
import csv

def extract_data(filename, column):
    with open(filename, 'r') as f:
        lines = [line.strip() for line in f if line.strip()]
    matrix = [list(map(float, line.split())) for line in lines]
    arr = np.array(matrix)
    return arr[:, column]

In [11]:
mat_source = scipy.io.loadmat("IR007_2.mat")
print(mat_source.keys())
print(mat_source["X107_DE_time"])
print(mat_source["X107_DE_time"].shape)

dict_keys(['__header__', '__version__', '__globals__', 'X107_DE_time', 'X107_FE_time', 'X107_BA_time', 'X107RPM'])
[[-0.09323776]
 [ 0.1872877 ]
 [ 0.21766307]
 ...
 [ 0.06562379]
 [-0.184039  ]
 [-0.04044635]]
(122136, 1)


In [17]:
for file_path in files: 
    mat_source = scipy.io.loadmat(example_mat)
    
    data = extract_data(file_path, 7)
    print(data)

    mat_source["X118_DE_time"] = np.array([[x] for x in data])
    file_name = file_path.name
    scipy.io.savemat(str(output_dir) + "/" + file_name + ".mat", mat_source)

[-0.21   0.054 -0.259 ... -0.149 -0.283 -0.347]
[-0.4    0.012  0.288 ... -0.117 -0.186 -0.183]
[-0.378 -0.251  0.281 ... -0.251 -0.254 -0.42 ]
[-0.112  0.2   -0.322 ...  0.076 -0.039 -0.098]
[-0.139 -0.095  0.142 ... -0.105 -0.081  0.042]
[-0.02  -0.081 -0.107 ... -0.007  0.105  0.232]
